package br.edu.ifsp.pep.visao;

import br.edu.ifsp.pep.visao.manutencao.*;
import com.formdev.flatlaf.FlatLightLaf;
import javax.swing.UIManager;

public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VisaoPrincipal
     */

    private int larguraFrame;
    private int alturaFrame;
    
    public TelaPrincipal() {
        initComponents();
        initMyComponents();
    }
    
    private void initMyComponents () {
        
        larguraFrame = 832;
        alturaFrame = 600;
        setSize(larguraFrame, alturaFrame);
        
        //formatarTabelas();
        setLocationRelativeTo(null);
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBackground = new javax.swing.JPanel();
        panelTituloPrincipal = new javax.swing.JPanel();
        labelTituloPrincipal = new javax.swing.JLabel();
        layeredPaneTelas = new javax.swing.JLayeredPane();
        panelTelaProprietarios = new javax.swing.JPanel();
        labelTituloProprietarios = new javax.swing.JLabel();
        labelIconeProprietarios = new javax.swing.JLabel();
        panelTelaLocatarios = new javax.swing.JPanel();
        labelTituloLocatarios = new javax.swing.JLabel();
        labelIconeLocatarios = new javax.swing.JLabel();
        panelTelaImoveis = new javax.swing.JPanel();
        labelTituloImoveis = new javax.swing.JLabel();
        labelIconeImoveis = new javax.swing.JLabel();
        panelTelaLocacoes = new javax.swing.JPanel();
        labelTituloLocacoes = new javax.swing.JLabel();
        labelIconeLocacoes = new javax.swing.JLabel();
        panelInferior = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de Imobiliária");
        setBackground(new java.awt.Color(0, 0, 0));
        setResizable(false);

        panelBackground.setBackground(new java.awt.Color(255, 255, 255));

        panelTituloPrincipal.setBackground(new java.awt.Color(25, 25, 25));
        panelTituloPrincipal.setForeground(new java.awt.Color(255, 255, 255));

        labelTituloPrincipal.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        labelTituloPrincipal.setForeground(new java.awt.Color(255, 255, 255));
        labelTituloPrincipal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTituloPrincipal.setText("Sistema de Imobiliária");

        javax.swing.GroupLayout panelTituloPrincipalLayout = new javax.swing.GroupLayout(panelTituloPrincipal);
        panelTituloPrincipal.setLayout(panelTituloPrincipalLayout);
        panelTituloPrincipalLayout.setHorizontalGroup(
            panelTituloPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelTituloPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 816, Short.MAX_VALUE)
        );
        panelTituloPrincipalLayout.setVerticalGroup(
            panelTituloPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTituloPrincipalLayout.createSequentialGroup()
                .addComponent(labelTituloPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        panelTelaProprietarios.setBackground(new java.awt.Color(204, 204, 204));
        panelTelaProprietarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelTelaProprietariosMouseClicked(evt);
            }
        });

        labelTituloProprietarios.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        labelTituloProprietarios.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTituloProprietarios.setText("Proprietários");

        labelIconeProprietarios.setIcon(new javax.swing.ImageIcon("C:\\Users\\crist\\Documents\\NetBeansProjects\\TrabalhoDiagramaDeClassesComBD\\res\\pessoa.png")); // NOI18N

        javax.swing.GroupLayout panelTelaProprietariosLayout = new javax.swing.GroupLayout(panelTelaProprietarios);
        panelTelaProprietarios.setLayout(panelTelaProprietariosLayout);
        panelTelaProprietariosLayout.setHorizontalGroup(
            panelTelaProprietariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTelaProprietariosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelTelaProprietariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelIconeProprietarios)
                    .addComponent(labelTituloProprietarios, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelTelaProprietariosLayout.setVerticalGroup(
            panelTelaProprietariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTelaProprietariosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelIconeProprietarios, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelTituloProprietarios)
                .addContainerGap())
        );

        panelTelaLocatarios.setBackground(new java.awt.Color(204, 204, 204));
        panelTelaLocatarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelTelaLocatariosMouseClicked(evt);
            }
        });

        labelTituloLocatarios.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        labelTituloLocatarios.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTituloLocatarios.setText("Locatários");

        labelIconeLocatarios.setIcon(new javax.swing.ImageIcon("C:\\Users\\crist\\Documents\\NetBeansProjects\\TrabalhoDiagramaDeClassesComBD\\res\\pessoa.png")); // NOI18N

        javax.swing.GroupLayout panelTelaLocatariosLayout = new javax.swing.GroupLayout(panelTelaLocatarios);
        panelTelaLocatarios.setLayout(panelTelaLocatariosLayout);
        panelTelaLocatariosLayout.setHorizontalGroup(
            panelTelaLocatariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTelaLocatariosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelTelaLocatariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelIconeLocatarios)
                    .addComponent(labelTituloLocatarios, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelTelaLocatariosLayout.setVerticalGroup(
            panelTelaLocatariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTelaLocatariosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelIconeLocatarios, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelTituloLocatarios)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelTelaImoveis.setBackground(new java.awt.Color(204, 204, 204));
        panelTelaImoveis.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelTelaImoveisMouseClicked(evt);
            }
        });

        labelTituloImoveis.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        labelTituloImoveis.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTituloImoveis.setText("Imóveis");

        labelIconeImoveis.setIcon(new javax.swing.ImageIcon("C:\\Users\\crist\\Documents\\NetBeansProjects\\TrabalhoDiagramaDeClassesComBD\\res\\imovel.png")); // NOI18N

        javax.swing.GroupLayout panelTelaImoveisLayout = new javax.swing.GroupLayout(panelTelaImoveis);
        panelTelaImoveis.setLayout(panelTelaImoveisLayout);
        panelTelaImoveisLayout.setHorizontalGroup(
            panelTelaImoveisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTelaImoveisLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelTituloImoveis, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTelaImoveisLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelIconeImoveis)
                .addContainerGap())
        );
        panelTelaImoveisLayout.setVerticalGroup(
            panelTelaImoveisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTelaImoveisLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelIconeImoveis, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelTituloImoveis)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelTelaLocacoes.setBackground(new java.awt.Color(204, 204, 204));
        panelTelaLocacoes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelTelaLocacoesMouseClicked(evt);
            }
        });

        labelTituloLocacoes.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        labelTituloLocacoes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTituloLocacoes.setText("Locações");

        labelIconeLocacoes.setIcon(new javax.swing.ImageIcon("C:\\Users\\crist\\Documents\\NetBeansProjects\\TrabalhoDiagramaDeClassesComBD\\res\\locacao.png")); // NOI18N

        javax.swing.GroupLayout panelTelaLocacoesLayout = new javax.swing.GroupLayout(panelTelaLocacoes);
        panelTelaLocacoes.setLayout(panelTelaLocacoesLayout);
        panelTelaLocacoesLayout.setHorizontalGroup(
            panelTelaLocacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTelaLocacoesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelTelaLocacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelTituloLocacoes, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelIconeLocacoes))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelTelaLocacoesLayout.setVerticalGroup(
            panelTelaLocacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTelaLocacoesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelIconeLocacoes, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelTituloLocacoes)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layeredPaneTelas.setLayer(panelTelaProprietarios, javax.swing.JLayeredPane.DEFAULT_LAYER);
        layeredPaneTelas.setLayer(panelTelaLocatarios, javax.swing.JLayeredPane.DEFAULT_LAYER);
        layeredPaneTelas.setLayer(panelTelaImoveis, javax.swing.JLayeredPane.DEFAULT_LAYER);
        layeredPaneTelas.setLayer(panelTelaLocacoes, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layeredPaneTelasLayout = new javax.swing.GroupLayout(layeredPaneTelas);
        layeredPaneTelas.setLayout(layeredPaneTelasLayout);
        layeredPaneTelasLayout.setHorizontalGroup(
            layeredPaneTelasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layeredPaneTelasLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(panelTelaProprietarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(panelTelaLocatarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(panelTelaImoveis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(panelTelaLocacoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layeredPaneTelasLayout.setVerticalGroup(
            layeredPaneTelasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layeredPaneTelasLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layeredPaneTelasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layeredPaneTelasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(panelTelaLocatarios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(panelTelaProprietarios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(panelTelaImoveis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(panelTelaLocacoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        panelInferior.setBackground(new java.awt.Color(25, 25, 25));
        panelInferior.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout panelInferiorLayout = new javax.swing.GroupLayout(panelInferior);
        panelInferior.setLayout(panelInferiorLayout);
        panelInferiorLayout.setHorizontalGroup(
            panelInferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panelInferiorLayout.setVerticalGroup(
            panelInferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 75, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panelBackgroundLayout = new javax.swing.GroupLayout(panelBackground);
        panelBackground.setLayout(panelBackgroundLayout);
        panelBackgroundLayout.setHorizontalGroup(
            panelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelInferior, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelTituloPrincipal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelBackgroundLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(layeredPaneTelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelBackgroundLayout.setVerticalGroup(
            panelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBackgroundLayout.createSequentialGroup()
                .addComponent(panelTituloPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(78, 78, 78)
                .addComponent(layeredPaneTelas)
                .addGap(146, 146, 146)
                .addComponent(panelInferior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void panelTelaProprietariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelTelaProprietariosMouseClicked
        TelaManutencaoProprietarios tmp;
        tmp = new TelaManutencaoProprietarios(this, true);
        tmp.setVisible(true);
    }//GEN-LAST:event_panelTelaProprietariosMouseClicked

    private void panelTelaImoveisMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelTelaImoveisMouseClicked
        TelaManutencaoImoveis tmi;
        tmi = new TelaManutencaoImoveis(this, true);
        tmi.setVisible(true);
    }//GEN-LAST:event_panelTelaImoveisMouseClicked

    private void panelTelaLocatariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelTelaLocatariosMouseClicked
        TelaManutencaoLocatarios tml;
        tml = new TelaManutencaoLocatarios(this, true);
        tml.setVisible(true);
    }//GEN-LAST:event_panelTelaLocatariosMouseClicked

    private void panelTelaLocacoesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelTelaLocacoesMouseClicked
        TelaManutencaoLocacoes tml;
        tml = new TelaManutencaoLocacoes(this, true);
        tml.setVisible(true);
    }//GEN-LAST:event_panelTelaLocacoesMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        /*
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("FlatLaf Light".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        */
        
        try {
            UIManager.setLookAndFeel(new FlatLightLaf());   
        } catch (Exception ex) {
            System.err.println("Erro ao iniciar o LAF.");
        }
        
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel labelIconeImoveis;
    private javax.swing.JLabel labelIconeLocacoes;
    private javax.swing.JLabel labelIconeLocatarios;
    private javax.swing.JLabel labelIconeProprietarios;
    private javax.swing.JLabel labelTituloImoveis;
    private javax.swing.JLabel labelTituloLocacoes;
    private javax.swing.JLabel labelTituloLocatarios;
    private javax.swing.JLabel labelTituloPrincipal;
    private javax.swing.JLabel labelTituloProprietarios;
    private javax.swing.JLayeredPane layeredPaneTelas;
    private javax.swing.JPanel panelBackground;
    private javax.swing.JPanel panelInferior;
    private javax.swing.JPanel panelTelaImoveis;
    private javax.swing.JPanel panelTelaLocacoes;
    private javax.swing.JPanel panelTelaLocatarios;
    private javax.swing.JPanel panelTelaProprietarios;
    private javax.swing.JPanel panelTituloPrincipal;
    // End of variables declaration//GEN-END:variables
}
