package br.edu.ifsp.pep.visao.manutencao;

import com.formdev.flatlaf.FlatLightLaf;
import javax.swing.UIManager;

public abstract class TelaManutencao extends javax.swing.JDialog {

    /**
     * Creates new form TelaManutencaoProprietarios
     * @param parent
     * @param modal
     */
    public TelaManutencao(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        initMyComponents();
    }
    
    private void initMyComponents () {
        setSize(832, 600);
        formatarTabelaDados();
        setResizable(false);
        setLocationRelativeTo(null);
    }
    
    public javax.swing.JLabel getLabelTituloPrincipal () {
        return labelTituloPrincipal;
    }
    
    public javax.swing.JTable getTableDados () {
        return tableDados;
    }
    
    public void definirTitulo (String titulo) {
        labelTituloPrincipal.setText(titulo);
    }
    
    public static void definirLaf () {
        try {
            UIManager.setLookAndFeel(new FlatLightLaf());   
        } catch (Exception ex) {
            System.err.println("Erro ao iniciar o LAF.");
        }
    }
    
    public static void centralizarColunas (javax.swing.JTable tableDados) {
        
        javax.swing.table.DefaultTableCellRenderer centerRenderer;
        centerRenderer = new javax.swing.table.DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(javax.swing.JLabel.CENTER);
        
        for (int i = 0; i < tableDados.getColumnCount(); i++) {
            tableDados.getColumnModel().getColumn(i).setCellRenderer(centerRenderer);
        }
        
    }
    
    private void formatarTabelaDados() {
        java.awt.Font headerFont = new java.awt.Font("Century Gothic",
                                                    1, 14);
        java.awt.Font tableFont = new java.awt.Font("Century Gothic",
                                                    0, 14);
        java.awt.Color headerColor = java.awt.Color.LIGHT_GRAY;
        
        tableDados.getTableHeader().setFont(headerFont);
        tableDados.getTableHeader().setBackground(headerColor);
        tableDados.setFont(tableFont);
        
    }
    
    public abstract void montarTabelaDados();
    public abstract void exibirTelaRegistro(String modo);
    public abstract void atualizarTabelaDados();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBackground = new javax.swing.JPanel();
        panelTituloPrincipal = new javax.swing.JPanel();
        labelTituloPrincipal = new javax.swing.JLabel();
        panelInferior = new javax.swing.JPanel();
        buttonCadastrar = new javax.swing.JButton();
        buttonAlterar = new javax.swing.JButton();
        buttonExibir = new javax.swing.JButton();
        buttonExcluir = new javax.swing.JButton();
        scrollPaneDados = new javax.swing.JScrollPane();
        tableDados = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        panelBackground.setBackground(new java.awt.Color(255, 255, 255));

        panelTituloPrincipal.setBackground(new java.awt.Color(25, 25, 25));
        panelTituloPrincipal.setForeground(new java.awt.Color(255, 255, 255));

        labelTituloPrincipal.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        labelTituloPrincipal.setForeground(new java.awt.Color(255, 255, 255));
        labelTituloPrincipal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout panelTituloPrincipalLayout = new javax.swing.GroupLayout(panelTituloPrincipal);
        panelTituloPrincipal.setLayout(panelTituloPrincipalLayout);
        panelTituloPrincipalLayout.setHorizontalGroup(
            panelTituloPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelTituloPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelTituloPrincipalLayout.setVerticalGroup(
            panelTituloPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTituloPrincipalLayout.createSequentialGroup()
                .addComponent(labelTituloPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        panelInferior.setBackground(new java.awt.Color(25, 25, 25));
        panelInferior.setForeground(new java.awt.Color(255, 255, 255));

        buttonCadastrar.setBackground(new java.awt.Color(242, 242, 242));
        buttonCadastrar.setFont(new java.awt.Font("Century Gothic", 1, 15)); // NOI18N
        buttonCadastrar.setText("Cadastrar");
        buttonCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCadastrarActionPerformed(evt);
            }
        });

        buttonAlterar.setBackground(new java.awt.Color(242, 242, 242));
        buttonAlterar.setFont(new java.awt.Font("Century Gothic", 1, 15)); // NOI18N
        buttonAlterar.setText("Alterar");
        buttonAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAlterarActionPerformed(evt);
            }
        });

        buttonExibir.setBackground(new java.awt.Color(242, 242, 242));
        buttonExibir.setFont(new java.awt.Font("Century Gothic", 1, 15)); // NOI18N
        buttonExibir.setText("Exibir");
        buttonExibir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonExibirActionPerformed(evt);
            }
        });

        buttonExcluir.setBackground(new java.awt.Color(242, 242, 242));
        buttonExcluir.setFont(new java.awt.Font("Century Gothic", 1, 15)); // NOI18N
        buttonExcluir.setText("Excluir");
        buttonExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonExcluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelInferiorLayout = new javax.swing.GroupLayout(panelInferior);
        panelInferior.setLayout(panelInferiorLayout);
        panelInferiorLayout.setHorizontalGroup(
            panelInferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInferiorLayout.createSequentialGroup()
                .addGap(156, 156, 156)
                .addComponent(buttonCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(buttonAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(buttonExibir, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(buttonExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(167, Short.MAX_VALUE))
        );
        panelInferiorLayout.setVerticalGroup(
            panelInferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelInferiorLayout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addGroup(panelInferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonExibir, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14))
        );

        tableDados.setBackground(new java.awt.Color(252, 252, 252));
        tableDados.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        tableDados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tableDados.getTableHeader().setReorderingAllowed(false);
        scrollPaneDados.setViewportView(tableDados);

        javax.swing.GroupLayout panelBackgroundLayout = new javax.swing.GroupLayout(panelBackground);
        panelBackground.setLayout(panelBackgroundLayout);
        panelBackgroundLayout.setHorizontalGroup(
            panelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelInferior, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelTituloPrincipal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelBackgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollPaneDados)
                .addContainerGap())
        );
        panelBackgroundLayout.setVerticalGroup(
            panelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBackgroundLayout.createSequentialGroup()
                .addComponent(panelTituloPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollPaneDados, javax.swing.GroupLayout.DEFAULT_SIZE, 401, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelInferior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 814, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panelBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 555, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panelBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAlterarActionPerformed
        exibirTelaRegistro("alterar");
        atualizarTabelaDados();
    }//GEN-LAST:event_buttonAlterarActionPerformed

    private void buttonExibirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonExibirActionPerformed
        exibirTelaRegistro("exibir");
    }//GEN-LAST:event_buttonExibirActionPerformed

    private void buttonExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonExcluirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonExcluirActionPerformed

    private void buttonCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCadastrarActionPerformed
        exibirTelaRegistro("cadastrar");
        atualizarTabelaDados();
    }//GEN-LAST:event_buttonCadastrarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAlterar;
    private javax.swing.JButton buttonCadastrar;
    private javax.swing.JButton buttonExcluir;
    private javax.swing.JButton buttonExibir;
    private javax.swing.JLabel labelTituloPrincipal;
    private javax.swing.JPanel panelBackground;
    private javax.swing.JPanel panelInferior;
    private javax.swing.JPanel panelTituloPrincipal;
    private javax.swing.JScrollPane scrollPaneDados;
    private javax.swing.JTable tableDados;
    // End of variables declaration//GEN-END:variables
}
