package br.edu.ifsp.pep.visao.manutencao.registro;

import com.formdev.flatlaf.FlatLightLaf;
import javax.swing.UIManager;

public class TelaRegistroLocatarios extends javax.swing.JDialog {
    
    private static String modo;

    /**
     * Creates new form TelaRegistroLocatarios
     * @param parent
     * @param modal
     * @param modo
     */
    public TelaRegistroLocatarios(java.awt.Frame parent, boolean modal, String modo) {
        super(parent, modal);
        initComponents();
        TelaRegistroLocatarios.modo = modo;
        initMyComponents();
    }
    

    private void initMyComponents () {
        setSize(832, 600);
        setResizable(false);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBackground = new javax.swing.JPanel();
        panelTituloPrincipal = new javax.swing.JPanel();
        labelTituloPrincipal = new javax.swing.JLabel();
        panelInferior = new javax.swing.JPanel();
        buttonConfirmar = new javax.swing.JButton();
        buttonVoltar = new javax.swing.JButton();
        panelCampoCpf = new javax.swing.JPanel();
        labelCampoCpf = new javax.swing.JLabel();
        textFieldCampoCpf = new javax.swing.JTextField();
        panelCampoNome = new javax.swing.JPanel();
        labelCampoNome = new javax.swing.JLabel();
        textFieldCampoNome = new javax.swing.JTextField();
        panelCampoEmail = new javax.swing.JPanel();
        labelCampoEmail = new javax.swing.JLabel();
        textFieldCampoEmail = new javax.swing.JTextField();
        panelCampoTelefone = new javax.swing.JPanel();
        labelCampoTelefone = new javax.swing.JLabel();
        textFieldCampoTelefone = new javax.swing.JTextField();
        panelCampoLimiteAluguel = new javax.swing.JPanel();
        labelCampoLimiteAluguel = new javax.swing.JLabel();
        textFieldCampoAluguel = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        panelBackground.setBackground(new java.awt.Color(255, 255, 255));

        panelTituloPrincipal.setBackground(new java.awt.Color(25, 25, 25));
        panelTituloPrincipal.setForeground(new java.awt.Color(255, 255, 255));

        labelTituloPrincipal.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        labelTituloPrincipal.setForeground(new java.awt.Color(255, 255, 255));
        labelTituloPrincipal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTituloPrincipal.setText("Locatário");

        javax.swing.GroupLayout panelTituloPrincipalLayout = new javax.swing.GroupLayout(panelTituloPrincipal);
        panelTituloPrincipal.setLayout(panelTituloPrincipalLayout);
        panelTituloPrincipalLayout.setHorizontalGroup(
            panelTituloPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelTituloPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelTituloPrincipalLayout.setVerticalGroup(
            panelTituloPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTituloPrincipalLayout.createSequentialGroup()
                .addComponent(labelTituloPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        panelInferior.setBackground(new java.awt.Color(25, 25, 25));
        panelInferior.setForeground(new java.awt.Color(255, 255, 255));

        buttonConfirmar.setBackground(new java.awt.Color(242, 242, 242));
        buttonConfirmar.setFont(new java.awt.Font("Century Gothic", 1, 15)); // NOI18N
        buttonConfirmar.setText("Confirmar");
        buttonConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonConfirmarActionPerformed(evt);
            }
        });

        buttonVoltar.setBackground(new java.awt.Color(242, 242, 242));
        buttonVoltar.setFont(new java.awt.Font("Century Gothic", 1, 15)); // NOI18N
        buttonVoltar.setText("Voltar");
        buttonVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonVoltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelInferiorLayout = new javax.swing.GroupLayout(panelInferior);
        panelInferior.setLayout(panelInferiorLayout);
        panelInferiorLayout.setHorizontalGroup(
            panelInferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInferiorLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(buttonConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(buttonVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelInferiorLayout.setVerticalGroup(
            panelInferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInferiorLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(panelInferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        panelCampoCpf.setBackground(new java.awt.Color(204, 204, 204));

        labelCampoCpf.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        labelCampoCpf.setText("CPF:");

        textFieldCampoCpf.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        textFieldCampoCpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldCampoCpfActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelCampoCpfLayout = new javax.swing.GroupLayout(panelCampoCpf);
        panelCampoCpf.setLayout(panelCampoCpfLayout);
        panelCampoCpfLayout.setHorizontalGroup(
            panelCampoCpfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCampoCpfLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelCampoCpf)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textFieldCampoCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelCampoCpfLayout.setVerticalGroup(
            panelCampoCpfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCampoCpfLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelCampoCpfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textFieldCampoCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelCampoCpf))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelCampoNome.setBackground(new java.awt.Color(204, 204, 204));

        labelCampoNome.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        labelCampoNome.setText("Nome:");

        textFieldCampoNome.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        textFieldCampoNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldCampoNomeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelCampoNomeLayout = new javax.swing.GroupLayout(panelCampoNome);
        panelCampoNome.setLayout(panelCampoNomeLayout);
        panelCampoNomeLayout.setHorizontalGroup(
            panelCampoNomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCampoNomeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelCampoNome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textFieldCampoNome, javax.swing.GroupLayout.DEFAULT_SIZE, 394, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelCampoNomeLayout.setVerticalGroup(
            panelCampoNomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCampoNomeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelCampoNomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textFieldCampoNome, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelCampoNome))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelCampoEmail.setBackground(new java.awt.Color(204, 204, 204));

        labelCampoEmail.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        labelCampoEmail.setText("Email:");

        textFieldCampoEmail.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        textFieldCampoEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldCampoEmailActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelCampoEmailLayout = new javax.swing.GroupLayout(panelCampoEmail);
        panelCampoEmail.setLayout(panelCampoEmailLayout);
        panelCampoEmailLayout.setHorizontalGroup(
            panelCampoEmailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCampoEmailLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelCampoEmail)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textFieldCampoEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 365, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelCampoEmailLayout.setVerticalGroup(
            panelCampoEmailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCampoEmailLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelCampoEmailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textFieldCampoEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelCampoEmail))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelCampoTelefone.setBackground(new java.awt.Color(204, 204, 204));

        labelCampoTelefone.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        labelCampoTelefone.setText("Telefone:");

        textFieldCampoTelefone.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        textFieldCampoTelefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldCampoTelefoneActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelCampoTelefoneLayout = new javax.swing.GroupLayout(panelCampoTelefone);
        panelCampoTelefone.setLayout(panelCampoTelefoneLayout);
        panelCampoTelefoneLayout.setHorizontalGroup(
            panelCampoTelefoneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCampoTelefoneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelCampoTelefone)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textFieldCampoTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelCampoTelefoneLayout.setVerticalGroup(
            panelCampoTelefoneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCampoTelefoneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelCampoTelefoneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textFieldCampoTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelCampoTelefone))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelCampoLimiteAluguel.setBackground(new java.awt.Color(204, 204, 204));

        labelCampoLimiteAluguel.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        labelCampoLimiteAluguel.setText("Limite de Aluguel (R$):");

        textFieldCampoAluguel.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        textFieldCampoAluguel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldCampoAluguelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelCampoLimiteAluguelLayout = new javax.swing.GroupLayout(panelCampoLimiteAluguel);
        panelCampoLimiteAluguel.setLayout(panelCampoLimiteAluguelLayout);
        panelCampoLimiteAluguelLayout.setHorizontalGroup(
            panelCampoLimiteAluguelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCampoLimiteAluguelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelCampoLimiteAluguel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textFieldCampoAluguel, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelCampoLimiteAluguelLayout.setVerticalGroup(
            panelCampoLimiteAluguelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCampoLimiteAluguelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelCampoLimiteAluguelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textFieldCampoAluguel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelCampoLimiteAluguel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelBackgroundLayout = new javax.swing.GroupLayout(panelBackground);
        panelBackground.setLayout(panelBackgroundLayout);
        panelBackgroundLayout.setHorizontalGroup(
            panelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelInferior, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelTituloPrincipal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelBackgroundLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(panelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelBackgroundLayout.createSequentialGroup()
                        .addComponent(panelCampoLimiteAluguel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panelBackgroundLayout.createSequentialGroup()
                        .addGroup(panelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelBackgroundLayout.createSequentialGroup()
                                .addComponent(panelCampoCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                                .addComponent(panelCampoNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelBackgroundLayout.createSequentialGroup()
                                .addComponent(panelCampoEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(panelCampoTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(22, 22, 22))))
        );
        panelBackgroundLayout.setVerticalGroup(
            panelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBackgroundLayout.createSequentialGroup()
                .addComponent(panelTituloPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelCampoCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelCampoNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelCampoEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelCampoTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(panelCampoLimiteAluguel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 209, Short.MAX_VALUE)
                .addComponent(panelInferior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 798, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panelBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 531, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panelBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonConfirmarActionPerformed

    }//GEN-LAST:event_buttonConfirmarActionPerformed

    private void buttonVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonVoltarActionPerformed
        dispose();
    }//GEN-LAST:event_buttonVoltarActionPerformed

    private void textFieldCampoCpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldCampoCpfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldCampoCpfActionPerformed

    private void textFieldCampoNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldCampoNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldCampoNomeActionPerformed

    private void textFieldCampoEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldCampoEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldCampoEmailActionPerformed

    private void textFieldCampoTelefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldCampoTelefoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldCampoTelefoneActionPerformed

    private void textFieldCampoAluguelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldCampoAluguelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldCampoAluguelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        try {
            UIManager.setLookAndFeel(new FlatLightLaf());   
        } catch (Exception ex) {
            System.err.println("Erro ao iniciar o LAF.");
        }
        
        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TelaRegistroLocatarios dialog = new TelaRegistroLocatarios(new javax.swing.JFrame(),
                                                                           true, modo);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonConfirmar;
    private javax.swing.JButton buttonVoltar;
    private javax.swing.JLabel labelCampoCpf;
    private javax.swing.JLabel labelCampoEmail;
    private javax.swing.JLabel labelCampoLimiteAluguel;
    private javax.swing.JLabel labelCampoNome;
    private javax.swing.JLabel labelCampoTelefone;
    private javax.swing.JLabel labelTituloPrincipal;
    private javax.swing.JPanel panelBackground;
    private javax.swing.JPanel panelCampoCpf;
    private javax.swing.JPanel panelCampoEmail;
    private javax.swing.JPanel panelCampoLimiteAluguel;
    private javax.swing.JPanel panelCampoNome;
    private javax.swing.JPanel panelCampoTelefone;
    private javax.swing.JPanel panelInferior;
    private javax.swing.JPanel panelTituloPrincipal;
    private javax.swing.JTextField textFieldCampoAluguel;
    private javax.swing.JTextField textFieldCampoCpf;
    private javax.swing.JTextField textFieldCampoEmail;
    private javax.swing.JTextField textFieldCampoNome;
    private javax.swing.JTextField textFieldCampoTelefone;
    // End of variables declaration//GEN-END:variables
}
