package br.edu.ifsp.pep.visao.manutencao.registro;

import com.formdev.flatlaf.FlatLightLaf;
import javax.swing.UIManager;

public class TelaRegistroImoveis extends javax.swing.JDialog {
    
     private static String modo;

    /**
     * Creates new form TelaRegistroImoveis
     * @param parent
     * @param modal
     * @param modo
     */
    public TelaRegistroImoveis(java.awt.Frame parent, boolean modal, String modo) {
        super(parent, modal);
        initComponents();
        TelaRegistroImoveis.modo = modo;
        initMyComponents();
    }
    
    private void initMyComponents () {
        setSize(832, 600);
        setResizable(false);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBackground = new javax.swing.JPanel();
        panelTituloPrincipal = new javax.swing.JPanel();
        labelTituloPrincipal = new javax.swing.JLabel();
        panelInferior = new javax.swing.JPanel();
        buttonConfirmar = new javax.swing.JButton();
        buttonVoltar = new javax.swing.JButton();
        panelCampoNumero = new javax.swing.JPanel();
        labelCampoNumero = new javax.swing.JLabel();
        textFieldCampoNumero = new javax.swing.JTextField();
        panelCampoEndereco = new javax.swing.JPanel();
        labelCampoEndereco = new javax.swing.JLabel();
        textFieldCampoEndereco = new javax.swing.JTextField();
        panelCampoBairro = new javax.swing.JPanel();
        labelCampoBairro = new javax.swing.JLabel();
        textFieldCampoBairro = new javax.swing.JTextField();
        panelCampoCidade = new javax.swing.JPanel();
        labelCampoCidade = new javax.swing.JLabel();
        textFieldCampoCidade = new javax.swing.JTextField();
        panelCampoEstado = new javax.swing.JPanel();
        labelCampoEstado = new javax.swing.JLabel();
        textFieldCampoEstado = new javax.swing.JTextField();
        panelCampoPadrao = new javax.swing.JPanel();
        labelCampoPadrao = new javax.swing.JLabel();
        comboBoxCampoPadrao = new javax.swing.JComboBox<>();
        panelCampoValorAluguel = new javax.swing.JPanel();
        labelCampoValorAluguel = new javax.swing.JLabel();
        textFieldCampoValorAluguel = new javax.swing.JTextField();
        panelCampoSituacao = new javax.swing.JPanel();
        labelCampoSituacao = new javax.swing.JLabel();
        comboBoxCampoSituacao = new javax.swing.JComboBox<>();
        panelCampoPercentualComissao = new javax.swing.JPanel();
        labelCampoPercentualComissao = new javax.swing.JLabel();
        textFieldCampoPercentualComissao = new javax.swing.JTextField();
        panelCampoProprietario = new javax.swing.JPanel();
        labelCampoProprietario = new javax.swing.JLabel();
        comboBoxCampoProprietario = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        panelBackground.setBackground(new java.awt.Color(255, 255, 255));

        panelTituloPrincipal.setBackground(new java.awt.Color(25, 25, 25));
        panelTituloPrincipal.setForeground(new java.awt.Color(255, 255, 255));

        labelTituloPrincipal.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        labelTituloPrincipal.setForeground(new java.awt.Color(255, 255, 255));
        labelTituloPrincipal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTituloPrincipal.setText("Imóvel");

        javax.swing.GroupLayout panelTituloPrincipalLayout = new javax.swing.GroupLayout(panelTituloPrincipal);
        panelTituloPrincipal.setLayout(panelTituloPrincipalLayout);
        panelTituloPrincipalLayout.setHorizontalGroup(
            panelTituloPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelTituloPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelTituloPrincipalLayout.setVerticalGroup(
            panelTituloPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTituloPrincipalLayout.createSequentialGroup()
                .addComponent(labelTituloPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        panelInferior.setBackground(new java.awt.Color(25, 25, 25));
        panelInferior.setForeground(new java.awt.Color(255, 255, 255));

        buttonConfirmar.setBackground(new java.awt.Color(242, 242, 242));
        buttonConfirmar.setFont(new java.awt.Font("Century Gothic", 1, 15)); // NOI18N
        buttonConfirmar.setText("Confirmar");
        buttonConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonConfirmarActionPerformed(evt);
            }
        });

        buttonVoltar.setBackground(new java.awt.Color(242, 242, 242));
        buttonVoltar.setFont(new java.awt.Font("Century Gothic", 1, 15)); // NOI18N
        buttonVoltar.setText("Voltar");
        buttonVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonVoltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelInferiorLayout = new javax.swing.GroupLayout(panelInferior);
        panelInferior.setLayout(panelInferiorLayout);
        panelInferiorLayout.setHorizontalGroup(
            panelInferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInferiorLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(buttonConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(buttonVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelInferiorLayout.setVerticalGroup(
            panelInferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInferiorLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(panelInferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        panelCampoNumero.setBackground(new java.awt.Color(204, 204, 204));

        labelCampoNumero.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        labelCampoNumero.setText("Número:");

        textFieldCampoNumero.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        textFieldCampoNumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldCampoNumeroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelCampoNumeroLayout = new javax.swing.GroupLayout(panelCampoNumero);
        panelCampoNumero.setLayout(panelCampoNumeroLayout);
        panelCampoNumeroLayout.setHorizontalGroup(
            panelCampoNumeroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCampoNumeroLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelCampoNumero)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textFieldCampoNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelCampoNumeroLayout.setVerticalGroup(
            panelCampoNumeroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCampoNumeroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelCampoNumeroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textFieldCampoNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelCampoNumero))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelCampoEndereco.setBackground(new java.awt.Color(204, 204, 204));

        labelCampoEndereco.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        labelCampoEndereco.setText("Endereço:");

        textFieldCampoEndereco.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        textFieldCampoEndereco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldCampoEnderecoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelCampoEnderecoLayout = new javax.swing.GroupLayout(panelCampoEndereco);
        panelCampoEndereco.setLayout(panelCampoEnderecoLayout);
        panelCampoEnderecoLayout.setHorizontalGroup(
            panelCampoEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCampoEnderecoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelCampoEndereco)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textFieldCampoEndereco, javax.swing.GroupLayout.DEFAULT_SIZE, 476, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelCampoEnderecoLayout.setVerticalGroup(
            panelCampoEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCampoEnderecoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelCampoEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textFieldCampoEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelCampoEndereco))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelCampoBairro.setBackground(new java.awt.Color(204, 204, 204));

        labelCampoBairro.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        labelCampoBairro.setText("Bairro:");

        textFieldCampoBairro.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        textFieldCampoBairro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldCampoBairroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelCampoBairroLayout = new javax.swing.GroupLayout(panelCampoBairro);
        panelCampoBairro.setLayout(panelCampoBairroLayout);
        panelCampoBairroLayout.setHorizontalGroup(
            panelCampoBairroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCampoBairroLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelCampoBairro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textFieldCampoBairro, javax.swing.GroupLayout.DEFAULT_SIZE, 365, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelCampoBairroLayout.setVerticalGroup(
            panelCampoBairroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCampoBairroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelCampoBairroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textFieldCampoBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelCampoBairro))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelCampoCidade.setBackground(new java.awt.Color(204, 204, 204));

        labelCampoCidade.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        labelCampoCidade.setText("Cidade:");

        textFieldCampoCidade.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        textFieldCampoCidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldCampoCidadeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelCampoCidadeLayout = new javax.swing.GroupLayout(panelCampoCidade);
        panelCampoCidade.setLayout(panelCampoCidadeLayout);
        panelCampoCidadeLayout.setHorizontalGroup(
            panelCampoCidadeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCampoCidadeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelCampoCidade)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textFieldCampoCidade, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelCampoCidadeLayout.setVerticalGroup(
            panelCampoCidadeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCampoCidadeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelCampoCidadeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textFieldCampoCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelCampoCidade))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelCampoEstado.setBackground(new java.awt.Color(204, 204, 204));

        labelCampoEstado.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        labelCampoEstado.setText("Estado:");

        textFieldCampoEstado.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        textFieldCampoEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldCampoEstadoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelCampoEstadoLayout = new javax.swing.GroupLayout(panelCampoEstado);
        panelCampoEstado.setLayout(panelCampoEstadoLayout);
        panelCampoEstadoLayout.setHorizontalGroup(
            panelCampoEstadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCampoEstadoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelCampoEstado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textFieldCampoEstado, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelCampoEstadoLayout.setVerticalGroup(
            panelCampoEstadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCampoEstadoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelCampoEstadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textFieldCampoEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelCampoEstado))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelCampoPadrao.setBackground(new java.awt.Color(204, 204, 204));

        labelCampoPadrao.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        labelCampoPadrao.setText("Padrão:");

        comboBoxCampoPadrao.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        comboBoxCampoPadrao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Alto", "Médio", "Popular" }));
        comboBoxCampoPadrao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxCampoPadraoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelCampoPadraoLayout = new javax.swing.GroupLayout(panelCampoPadrao);
        panelCampoPadrao.setLayout(panelCampoPadraoLayout);
        panelCampoPadraoLayout.setHorizontalGroup(
            panelCampoPadraoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCampoPadraoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelCampoPadrao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comboBoxCampoPadrao, 0, 131, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelCampoPadraoLayout.setVerticalGroup(
            panelCampoPadraoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCampoPadraoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelCampoPadraoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(comboBoxCampoPadrao)
                    .addComponent(labelCampoPadrao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        panelCampoValorAluguel.setBackground(new java.awt.Color(204, 204, 204));

        labelCampoValorAluguel.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        labelCampoValorAluguel.setText("Aluguel (R$):");

        textFieldCampoValorAluguel.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        textFieldCampoValorAluguel.setToolTipText("");
        textFieldCampoValorAluguel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldCampoValorAluguelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelCampoValorAluguelLayout = new javax.swing.GroupLayout(panelCampoValorAluguel);
        panelCampoValorAluguel.setLayout(panelCampoValorAluguelLayout);
        panelCampoValorAluguelLayout.setHorizontalGroup(
            panelCampoValorAluguelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCampoValorAluguelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelCampoValorAluguel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textFieldCampoValorAluguel, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelCampoValorAluguelLayout.setVerticalGroup(
            panelCampoValorAluguelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCampoValorAluguelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelCampoValorAluguelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textFieldCampoValorAluguel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelCampoValorAluguel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        textFieldCampoValorAluguel.getAccessibleContext().setAccessibleName("");

        panelCampoSituacao.setBackground(new java.awt.Color(204, 204, 204));

        labelCampoSituacao.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        labelCampoSituacao.setText("Situação:");

        comboBoxCampoSituacao.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        comboBoxCampoSituacao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Locado", "Disponível" }));
        comboBoxCampoSituacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxCampoSituacaoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelCampoSituacaoLayout = new javax.swing.GroupLayout(panelCampoSituacao);
        panelCampoSituacao.setLayout(panelCampoSituacaoLayout);
        panelCampoSituacaoLayout.setHorizontalGroup(
            panelCampoSituacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCampoSituacaoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelCampoSituacao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comboBoxCampoSituacao, 0, 131, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelCampoSituacaoLayout.setVerticalGroup(
            panelCampoSituacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCampoSituacaoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelCampoSituacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(comboBoxCampoSituacao)
                    .addComponent(labelCampoSituacao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        panelCampoPercentualComissao.setBackground(new java.awt.Color(204, 204, 204));

        labelCampoPercentualComissao.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        labelCampoPercentualComissao.setText("Comissão (%):");

        textFieldCampoPercentualComissao.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        textFieldCampoPercentualComissao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldCampoPercentualComissaoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelCampoPercentualComissaoLayout = new javax.swing.GroupLayout(panelCampoPercentualComissao);
        panelCampoPercentualComissao.setLayout(panelCampoPercentualComissaoLayout);
        panelCampoPercentualComissaoLayout.setHorizontalGroup(
            panelCampoPercentualComissaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCampoPercentualComissaoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelCampoPercentualComissao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textFieldCampoPercentualComissao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelCampoPercentualComissaoLayout.setVerticalGroup(
            panelCampoPercentualComissaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCampoPercentualComissaoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelCampoPercentualComissaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textFieldCampoPercentualComissao, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelCampoPercentualComissao))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelCampoProprietario.setBackground(new java.awt.Color(204, 204, 204));

        labelCampoProprietario.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        labelCampoProprietario.setText("Proprietário:");

        comboBoxCampoProprietario.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        comboBoxCampoProprietario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxCampoProprietarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelCampoProprietarioLayout = new javax.swing.GroupLayout(panelCampoProprietario);
        panelCampoProprietario.setLayout(panelCampoProprietarioLayout);
        panelCampoProprietarioLayout.setHorizontalGroup(
            panelCampoProprietarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCampoProprietarioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelCampoProprietario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comboBoxCampoProprietario, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelCampoProprietarioLayout.setVerticalGroup(
            panelCampoProprietarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCampoProprietarioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelCampoProprietarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(comboBoxCampoProprietario)
                    .addComponent(labelCampoProprietario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout panelBackgroundLayout = new javax.swing.GroupLayout(panelBackground);
        panelBackground.setLayout(panelBackgroundLayout);
        panelBackgroundLayout.setHorizontalGroup(
            panelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelInferior, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelTituloPrincipal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelBackgroundLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(panelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelBackgroundLayout.createSequentialGroup()
                        .addComponent(panelCampoSituacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(panelCampoPercentualComissao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49)
                        .addComponent(panelCampoProprietario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panelBackgroundLayout.createSequentialGroup()
                        .addComponent(panelCampoBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(panelCampoCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelBackgroundLayout.createSequentialGroup()
                        .addComponent(panelCampoNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                        .addComponent(panelCampoEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelBackgroundLayout.createSequentialGroup()
                        .addComponent(panelCampoEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addComponent(panelCampoPadrao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(panelCampoValorAluguel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(21, 21, 21))
        );
        panelBackgroundLayout.setVerticalGroup(
            panelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBackgroundLayout.createSequentialGroup()
                .addComponent(panelTituloPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelCampoNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelCampoEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelCampoBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelCampoCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelCampoEstado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelCampoValorAluguel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelCampoPadrao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(panelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelCampoSituacao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelCampoPercentualComissao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelCampoProprietario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 153, Short.MAX_VALUE)
                .addComponent(panelInferior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 798, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panelBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 535, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panelBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonConfirmarActionPerformed

    }//GEN-LAST:event_buttonConfirmarActionPerformed

    private void buttonVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonVoltarActionPerformed
        dispose();
    }//GEN-LAST:event_buttonVoltarActionPerformed

    private void textFieldCampoNumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldCampoNumeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldCampoNumeroActionPerformed

    private void textFieldCampoEnderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldCampoEnderecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldCampoEnderecoActionPerformed

    private void textFieldCampoBairroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldCampoBairroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldCampoBairroActionPerformed

    private void textFieldCampoCidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldCampoCidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldCampoCidadeActionPerformed

    private void textFieldCampoEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldCampoEstadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldCampoEstadoActionPerformed

    private void textFieldCampoValorAluguelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldCampoValorAluguelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldCampoValorAluguelActionPerformed

    private void comboBoxCampoPadraoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxCampoPadraoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboBoxCampoPadraoActionPerformed

    private void comboBoxCampoSituacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxCampoSituacaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboBoxCampoSituacaoActionPerformed

    private void textFieldCampoPercentualComissaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldCampoPercentualComissaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldCampoPercentualComissaoActionPerformed

    private void comboBoxCampoProprietarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxCampoProprietarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboBoxCampoProprietarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        try {
            UIManager.setLookAndFeel(new FlatLightLaf());   
        } catch (Exception ex) {
            System.err.println("Erro ao iniciar o LAF.");
        }

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TelaRegistroImoveis dialog = new TelaRegistroImoveis(new javax.swing.JFrame(),
                                                                true, modo);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonConfirmar;
    private javax.swing.JButton buttonVoltar;
    private javax.swing.JComboBox<String> comboBoxCampoPadrao;
    private javax.swing.JComboBox<String> comboBoxCampoProprietario;
    private javax.swing.JComboBox<String> comboBoxCampoSituacao;
    private javax.swing.JLabel labelCampoBairro;
    private javax.swing.JLabel labelCampoCidade;
    private javax.swing.JLabel labelCampoEndereco;
    private javax.swing.JLabel labelCampoEstado;
    private javax.swing.JLabel labelCampoNumero;
    private javax.swing.JLabel labelCampoPadrao;
    private javax.swing.JLabel labelCampoPercentualComissao;
    private javax.swing.JLabel labelCampoProprietario;
    private javax.swing.JLabel labelCampoSituacao;
    private javax.swing.JLabel labelCampoValorAluguel;
    private javax.swing.JLabel labelTituloPrincipal;
    private javax.swing.JPanel panelBackground;
    private javax.swing.JPanel panelCampoBairro;
    private javax.swing.JPanel panelCampoCidade;
    private javax.swing.JPanel panelCampoEndereco;
    private javax.swing.JPanel panelCampoEstado;
    private javax.swing.JPanel panelCampoNumero;
    private javax.swing.JPanel panelCampoPadrao;
    private javax.swing.JPanel panelCampoPercentualComissao;
    private javax.swing.JPanel panelCampoProprietario;
    private javax.swing.JPanel panelCampoSituacao;
    private javax.swing.JPanel panelCampoValorAluguel;
    private javax.swing.JPanel panelInferior;
    private javax.swing.JPanel panelTituloPrincipal;
    private javax.swing.JTextField textFieldCampoBairro;
    private javax.swing.JTextField textFieldCampoCidade;
    private javax.swing.JTextField textFieldCampoEndereco;
    private javax.swing.JTextField textFieldCampoEstado;
    private javax.swing.JTextField textFieldCampoNumero;
    private javax.swing.JTextField textFieldCampoPercentualComissao;
    private javax.swing.JTextField textFieldCampoValorAluguel;
    // End of variables declaration//GEN-END:variables
}
