package br.edu.ifsp.pep.visao.manutencao.registro;

import br.edu.ifsp.pep.visao.manutencao.TelaPagamentos;
import com.formdev.flatlaf.FlatLightLaf;
import javax.swing.UIManager;

public class TelaRegistroLocacoes extends javax.swing.JDialog {

    private static String modo;
    
    /**
     * Creates new form TelaRegistroLocacoes
     * @param parent
     * @param modal
     * @param modo
     */
    public TelaRegistroLocacoes(java.awt.Frame parent, boolean modal, String modo) {
        super(parent, modal);
        initComponents();
        TelaRegistroLocacoes.modo = modo;
        initMyComponents();
    }
    
    private void initMyComponents () {
        setSize(832, 600);
        setResizable(false);
        
        if (modo.equals("exibir"))
            buttonPagamentos.setVisible(true);
        else
            buttonPagamentos.setVisible(false);
        
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBackground = new javax.swing.JPanel();
        panelTituloPrincipal = new javax.swing.JPanel();
        labelTituloPrincipal = new javax.swing.JLabel();
        panelInferior = new javax.swing.JPanel();
        buttonConfirmar = new javax.swing.JButton();
        buttonVoltar = new javax.swing.JButton();
        buttonPagamentos = new javax.swing.JButton();
        panelCampoNumeroContrato = new javax.swing.JPanel();
        labelCampoNumeroContrato = new javax.swing.JLabel();
        textFieldCampoNumeroContrato = new javax.swing.JTextField();
        panelCampoDataContrato = new javax.swing.JPanel();
        labelCampoDataContrato = new javax.swing.JLabel();
        formattedTextFieldDataContrato = new javax.swing.JFormattedTextField();
        panelCampoPrazoContrato = new javax.swing.JPanel();
        labelCampoPrazoContrato = new javax.swing.JLabel();
        textFieldCampoPrazoContrato = new javax.swing.JTextField();
        panelCampoValorAluguel = new javax.swing.JPanel();
        labelCampoValorAluguel = new javax.swing.JLabel();
        textFieldCampoValorAluguel = new javax.swing.JTextField();
        panelCampoDiaVencimento = new javax.swing.JPanel();
        labelCampoDiaVencimento = new javax.swing.JLabel();
        textFieldCampoDiaVencimento = new javax.swing.JTextField();
        panelCampoImovel = new javax.swing.JPanel();
        labelCampoImovel = new javax.swing.JLabel();
        comboBoxCampoImovel = new javax.swing.JComboBox<>();
        panelCampoLocatario = new javax.swing.JPanel();
        labelCampoLocatario = new javax.swing.JLabel();
        comboBoxCampoLocatario = new javax.swing.JComboBox<>();
        panelFormatacaoTamanho = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        panelBackground.setBackground(new java.awt.Color(255, 255, 255));

        panelTituloPrincipal.setBackground(new java.awt.Color(25, 25, 25));
        panelTituloPrincipal.setForeground(new java.awt.Color(255, 255, 255));

        labelTituloPrincipal.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        labelTituloPrincipal.setForeground(new java.awt.Color(255, 255, 255));
        labelTituloPrincipal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTituloPrincipal.setText("Locação");

        javax.swing.GroupLayout panelTituloPrincipalLayout = new javax.swing.GroupLayout(panelTituloPrincipal);
        panelTituloPrincipal.setLayout(panelTituloPrincipalLayout);
        panelTituloPrincipalLayout.setHorizontalGroup(
            panelTituloPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelTituloPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelTituloPrincipalLayout.setVerticalGroup(
            panelTituloPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTituloPrincipalLayout.createSequentialGroup()
                .addComponent(labelTituloPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        panelInferior.setBackground(new java.awt.Color(25, 25, 25));
        panelInferior.setForeground(new java.awt.Color(255, 255, 255));

        buttonConfirmar.setBackground(new java.awt.Color(242, 242, 242));
        buttonConfirmar.setFont(new java.awt.Font("Century Gothic", 1, 15)); // NOI18N
        buttonConfirmar.setText("Confirmar");
        buttonConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonConfirmarActionPerformed(evt);
            }
        });

        buttonVoltar.setBackground(new java.awt.Color(242, 242, 242));
        buttonVoltar.setFont(new java.awt.Font("Century Gothic", 1, 15)); // NOI18N
        buttonVoltar.setText("Voltar");
        buttonVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonVoltarActionPerformed(evt);
            }
        });

        buttonPagamentos.setBackground(new java.awt.Color(242, 242, 242));
        buttonPagamentos.setFont(new java.awt.Font("Century Gothic", 1, 15)); // NOI18N
        buttonPagamentos.setText("Mensalidades");
        buttonPagamentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPagamentosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelInferiorLayout = new javax.swing.GroupLayout(panelInferior);
        panelInferior.setLayout(panelInferiorLayout);
        panelInferiorLayout.setHorizontalGroup(
            panelInferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInferiorLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(buttonConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(buttonVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(125, 125, 125)
                .addComponent(buttonPagamentos)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelInferiorLayout.setVerticalGroup(
            panelInferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInferiorLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(panelInferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonPagamentos, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        panelCampoNumeroContrato.setBackground(new java.awt.Color(204, 204, 204));

        labelCampoNumeroContrato.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        labelCampoNumeroContrato.setText("Contrato:");

        textFieldCampoNumeroContrato.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        textFieldCampoNumeroContrato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldCampoNumeroContratoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelCampoNumeroContratoLayout = new javax.swing.GroupLayout(panelCampoNumeroContrato);
        panelCampoNumeroContrato.setLayout(panelCampoNumeroContratoLayout);
        panelCampoNumeroContratoLayout.setHorizontalGroup(
            panelCampoNumeroContratoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCampoNumeroContratoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelCampoNumeroContrato)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textFieldCampoNumeroContrato, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelCampoNumeroContratoLayout.setVerticalGroup(
            panelCampoNumeroContratoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCampoNumeroContratoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelCampoNumeroContratoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textFieldCampoNumeroContrato, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelCampoNumeroContrato))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelCampoDataContrato.setBackground(new java.awt.Color(204, 204, 204));

        labelCampoDataContrato.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        labelCampoDataContrato.setText("Data (dd/mm/aaaa):");

        formattedTextFieldDataContrato.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.SHORT))));

        javax.swing.GroupLayout panelCampoDataContratoLayout = new javax.swing.GroupLayout(panelCampoDataContrato);
        panelCampoDataContrato.setLayout(panelCampoDataContratoLayout);
        panelCampoDataContratoLayout.setHorizontalGroup(
            panelCampoDataContratoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCampoDataContratoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelCampoDataContrato)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(formattedTextFieldDataContrato, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelCampoDataContratoLayout.setVerticalGroup(
            panelCampoDataContratoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCampoDataContratoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelCampoDataContratoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelCampoDataContratoLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(labelCampoDataContrato, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(formattedTextFieldDataContrato, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
                .addContainerGap())
        );

        panelCampoPrazoContrato.setBackground(new java.awt.Color(204, 204, 204));

        labelCampoPrazoContrato.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        labelCampoPrazoContrato.setText("Prazo:");

        textFieldCampoPrazoContrato.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        textFieldCampoPrazoContrato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldCampoPrazoContratoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelCampoPrazoContratoLayout = new javax.swing.GroupLayout(panelCampoPrazoContrato);
        panelCampoPrazoContrato.setLayout(panelCampoPrazoContratoLayout);
        panelCampoPrazoContratoLayout.setHorizontalGroup(
            panelCampoPrazoContratoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCampoPrazoContratoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelCampoPrazoContrato)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textFieldCampoPrazoContrato)
                .addContainerGap())
        );
        panelCampoPrazoContratoLayout.setVerticalGroup(
            panelCampoPrazoContratoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCampoPrazoContratoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelCampoPrazoContratoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textFieldCampoPrazoContrato, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelCampoPrazoContrato))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelCampoValorAluguel.setBackground(new java.awt.Color(204, 204, 204));

        labelCampoValorAluguel.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        labelCampoValorAluguel.setText("Valor do Aluguel (R$):");

        textFieldCampoValorAluguel.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        textFieldCampoValorAluguel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldCampoValorAluguelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelCampoValorAluguelLayout = new javax.swing.GroupLayout(panelCampoValorAluguel);
        panelCampoValorAluguel.setLayout(panelCampoValorAluguelLayout);
        panelCampoValorAluguelLayout.setHorizontalGroup(
            panelCampoValorAluguelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCampoValorAluguelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelCampoValorAluguel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textFieldCampoValorAluguel, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelCampoValorAluguelLayout.setVerticalGroup(
            panelCampoValorAluguelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCampoValorAluguelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelCampoValorAluguelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textFieldCampoValorAluguel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelCampoValorAluguel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelCampoDiaVencimento.setBackground(new java.awt.Color(204, 204, 204));

        labelCampoDiaVencimento.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        labelCampoDiaVencimento.setText("Dia de Vencimento:");

        textFieldCampoDiaVencimento.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        textFieldCampoDiaVencimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldCampoDiaVencimentoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelCampoDiaVencimentoLayout = new javax.swing.GroupLayout(panelCampoDiaVencimento);
        panelCampoDiaVencimento.setLayout(panelCampoDiaVencimentoLayout);
        panelCampoDiaVencimentoLayout.setHorizontalGroup(
            panelCampoDiaVencimentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCampoDiaVencimentoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelCampoDiaVencimento)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textFieldCampoDiaVencimento, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelCampoDiaVencimentoLayout.setVerticalGroup(
            panelCampoDiaVencimentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCampoDiaVencimentoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelCampoDiaVencimentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textFieldCampoDiaVencimento, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelCampoDiaVencimento))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelCampoImovel.setBackground(new java.awt.Color(204, 204, 204));

        labelCampoImovel.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        labelCampoImovel.setText("Imóvel:");

        comboBoxCampoImovel.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        comboBoxCampoImovel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxCampoImovelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelCampoImovelLayout = new javax.swing.GroupLayout(panelCampoImovel);
        panelCampoImovel.setLayout(panelCampoImovelLayout);
        panelCampoImovelLayout.setHorizontalGroup(
            panelCampoImovelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCampoImovelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelCampoImovel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comboBoxCampoImovel, 0, 82, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelCampoImovelLayout.setVerticalGroup(
            panelCampoImovelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCampoImovelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelCampoImovelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(comboBoxCampoImovel, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(labelCampoImovel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        panelCampoLocatario.setBackground(new java.awt.Color(204, 204, 204));

        labelCampoLocatario.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        labelCampoLocatario.setText("Locatário:");

        comboBoxCampoLocatario.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        comboBoxCampoLocatario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxCampoLocatarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelCampoLocatarioLayout = new javax.swing.GroupLayout(panelCampoLocatario);
        panelCampoLocatario.setLayout(panelCampoLocatarioLayout);
        panelCampoLocatarioLayout.setHorizontalGroup(
            panelCampoLocatarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCampoLocatarioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelCampoLocatario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comboBoxCampoLocatario, 0, 218, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelCampoLocatarioLayout.setVerticalGroup(
            panelCampoLocatarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCampoLocatarioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelCampoLocatarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(comboBoxCampoLocatario, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                    .addComponent(labelCampoLocatario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        panelFormatacaoTamanho.setOpaque(false);

        javax.swing.GroupLayout panelFormatacaoTamanhoLayout = new javax.swing.GroupLayout(panelFormatacaoTamanho);
        panelFormatacaoTamanho.setLayout(panelFormatacaoTamanhoLayout);
        panelFormatacaoTamanhoLayout.setHorizontalGroup(
            panelFormatacaoTamanhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );
        panelFormatacaoTamanhoLayout.setVerticalGroup(
            panelFormatacaoTamanhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 43, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panelBackgroundLayout = new javax.swing.GroupLayout(panelBackground);
        panelBackground.setLayout(panelBackgroundLayout);
        panelBackgroundLayout.setHorizontalGroup(
            panelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelInferior, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelTituloPrincipal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelBackgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelFormatacaoTamanho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelBackgroundLayout.createSequentialGroup()
                        .addComponent(panelCampoLocatario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 457, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelBackgroundLayout.createSequentialGroup()
                            .addComponent(panelCampoNumeroContrato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(panelCampoDataContrato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(49, 49, 49)
                            .addComponent(panelCampoPrazoContrato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(panelBackgroundLayout.createSequentialGroup()
                            .addComponent(panelCampoValorAluguel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(54, 54, 54)
                            .addComponent(panelCampoDiaVencimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(panelCampoImovel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(33, 33, 33))
        );
        panelBackgroundLayout.setVerticalGroup(
            panelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBackgroundLayout.createSequentialGroup()
                .addComponent(panelTituloPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelBackgroundLayout.createSequentialGroup()
                        .addGroup(panelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(panelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(panelCampoNumeroContrato, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(panelCampoDataContrato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(panelCampoPrazoContrato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(panelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(panelCampoValorAluguel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(panelCampoDiaVencimento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(panelCampoImovel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(panelCampoLocatario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(panelFormatacaoTamanho, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 212, Short.MAX_VALUE)
                .addComponent(panelInferior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 807, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panelBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 535, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panelBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonConfirmarActionPerformed

    }//GEN-LAST:event_buttonConfirmarActionPerformed

    private void buttonVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonVoltarActionPerformed
        dispose();
    }//GEN-LAST:event_buttonVoltarActionPerformed

    private void textFieldCampoNumeroContratoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldCampoNumeroContratoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldCampoNumeroContratoActionPerformed

    private void textFieldCampoPrazoContratoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldCampoPrazoContratoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldCampoPrazoContratoActionPerformed

    private void textFieldCampoValorAluguelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldCampoValorAluguelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldCampoValorAluguelActionPerformed

    private void textFieldCampoDiaVencimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldCampoDiaVencimentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldCampoDiaVencimentoActionPerformed

    private void comboBoxCampoImovelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxCampoImovelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboBoxCampoImovelActionPerformed

    private void comboBoxCampoLocatarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxCampoLocatarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboBoxCampoLocatarioActionPerformed

    private void buttonPagamentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPagamentosActionPerformed
        TelaPagamentos tp = new TelaPagamentos(new javax.swing.JFrame(), true);
        tp.setVisible(true);
    }//GEN-LAST:event_buttonPagamentosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        try {
            UIManager.setLookAndFeel(new FlatLightLaf());   
        } catch (Exception ex) {
            System.err.println("Erro ao iniciar o LAF.");
        }

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TelaRegistroLocacoes dialog = new TelaRegistroLocacoes(new javax.swing.JFrame(),
                                                                       true, modo);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonConfirmar;
    private javax.swing.JButton buttonPagamentos;
    private javax.swing.JButton buttonVoltar;
    private javax.swing.JComboBox<String> comboBoxCampoImovel;
    private javax.swing.JComboBox<String> comboBoxCampoLocatario;
    private javax.swing.JFormattedTextField formattedTextFieldDataContrato;
    private javax.swing.JLabel labelCampoDataContrato;
    private javax.swing.JLabel labelCampoDiaVencimento;
    private javax.swing.JLabel labelCampoImovel;
    private javax.swing.JLabel labelCampoLocatario;
    private javax.swing.JLabel labelCampoNumeroContrato;
    private javax.swing.JLabel labelCampoPrazoContrato;
    private javax.swing.JLabel labelCampoValorAluguel;
    private javax.swing.JLabel labelTituloPrincipal;
    private javax.swing.JPanel panelBackground;
    private javax.swing.JPanel panelCampoDataContrato;
    private javax.swing.JPanel panelCampoDiaVencimento;
    private javax.swing.JPanel panelCampoImovel;
    private javax.swing.JPanel panelCampoLocatario;
    private javax.swing.JPanel panelCampoNumeroContrato;
    private javax.swing.JPanel panelCampoPrazoContrato;
    private javax.swing.JPanel panelCampoValorAluguel;
    private javax.swing.JPanel panelFormatacaoTamanho;
    private javax.swing.JPanel panelInferior;
    private javax.swing.JPanel panelTituloPrincipal;
    private javax.swing.JTextField textFieldCampoDiaVencimento;
    private javax.swing.JTextField textFieldCampoNumeroContrato;
    private javax.swing.JTextField textFieldCampoPrazoContrato;
    private javax.swing.JTextField textFieldCampoValorAluguel;
    // End of variables declaration//GEN-END:variables
}
